// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2cPWXv1ZboXQ7oIdJ5K-rWC3BlANcIeo',
    appId: '1:1006366011872:web:dfcf425f990f15f8913b85',
    messagingSenderId: '1006366011872',
    projectId: 'ordering-system-client-3d9a1',
    authDomain: 'ordering-system-client-3d9a1.firebaseapp.com',
    storageBucket: 'ordering-system-client-3d9a1.appspot.com',
    measurementId: 'G-FSDLE4SBHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf9OhE7vxgvu9Zx3BaZ5wCYkDJPKNRULA',
    appId: '1:1006366011872:android:24c628b1692ffefc913b85',
    messagingSenderId: '1006366011872',
    projectId: 'ordering-system-client-3d9a1',
    storageBucket: 'ordering-system-client-3d9a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGGuL-GmLtSINQuX_8hx07cb8qXDvKs40',
    appId: '1:1006366011872:ios:9e24b3a5098f62c7913b85',
    messagingSenderId: '1006366011872',
    projectId: 'ordering-system-client-3d9a1',
    storageBucket: 'ordering-system-client-3d9a1.appspot.com',
    iosBundleId: 'com.example.orderingSystemClientApp',
  );
}
